swagger:
  applications:
      -
        name: MyTaxi Assessment
        version: 2.0
        url: https://mytaxi-assessment.herokuapp.com/v2/api-docs
      -
        name: Glovo Assessment
        version: 2.0
        url: https://glovo-assessment.herokuapp.com/v2/api-docs
      -
        name: WAES Assessment
        version: 2.0
        url: https://waes-assessment.herokuapp.com/v2/api-docs
      -
        name: N26 Assessment
        version: 2.0
        url: https://n26-assessment.herokuapp.com/v2/api-docs
